### ISSUE TITLE
Stealthwatch 7.0 Support

### ISSUE THREAD

**Issue by Ucnt** [CiscoDevNet/stealthwatch-data-exporter#3]
Upcoming Stealthatch 7.0 support requires that devices include the full chain of certs, not just the CA cert.  I have tested RC3 and confirmed that you need up upload both certs for the data exporter to work.  Requesting documentation be changed to state:

**In Stealthwatch versions prior to 7.0:**    
Import `certs/data-exporter-certificate-authority.crt` into the Flow Collector via the 
`Configuration -> Certificate Authority Certificates` menu.

**In Stealthwatch versions 7.0 and above:**
Import `certs/data-exporter-certificate-authority.crt` **and `certs/data-exporter.crt`** into the Flow Collector via the 
`Configuration -> Certificate Authority Certificates` menu.

**Comment by tomgagnier** [comment]
README has been updated to include these instructions.
